### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 2: invalid start byte Unknown contract: Stock(symbol='AAPL', exchange='SMART', currency='USD')

### ISSUE THREAD

**Issue by viponedream** [erdewit/ib_insync#121] opened 2019-01-01 05:06 UTC
spx = Stock('AAPL', 'SMART', 'USD')
ib.qualifyContracts(spx)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 2: invalid start byte
Unknown contract: Stock(symbol='AAPL', exchange='SMART', currency='USD')

and the i debug , i found in decorder.py
def processContractDataMsg(self, fields):
        if version >= 5:
            contract.longName = decode(str, fields)    ---> this line 

when it tr to decode    b'\xc6\xbb\xb9\xfb\xb9\xab\xcb\xbe-APPLE INC'
it return the wrong message

**Comment by erdewit** [comment] 2019-01-01 16:20
Duplicate of InteractiveBrokers/tws-api#775

**Closed by erdewit** 2019-01-01 16:20 UTC
