### ISSUE TITLE
unexpected behavior of ib.trades() on v0.9.63

### ISSUE THREAD

**Issue by peachy88** [erdewit/ib_insync#309] opened 2020-10-31 09:22 UTC
Hello,

ib.trades() in latest version does not include fills anymore. see below :

v0.9.63 :

Trade(contract=Stock(conId=395196161, symbol='BILL', right='?', exchange='SMART', currency='USD', localSymbol='BILL', tradingClass='BILL'), order=Order(permId=1363301119, action='SELL', orderType='STP', lmtPrice=0.0, auxPrice=104.62, tif='GTC', ocaType=3, orderRef='', rule80A='0', trailStopPrice=104.62, openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='', clearingIntent='IB', cashQty=0.0, dontUseAutoPriceForHedge=True, autoCancelDate='20210331 23:00:00 CET', filledQuantity=26.0, refFuturesConId=2147483647, shareholder='Not an insider or substantial shareholder'), orderStatus=OrderStatus(orderId=0, status='Filled', filled=0, remaining=0, avgFillPrice=0.0, permId=0, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0), fills=[], log=[])

v0.9.62 :

Trade(contract=Stock(conId=395196161, symbol='BILL', right='?', exchange='SMART', currency='USD', localSymbol='BILL', tradingClass='BILL'), order=Order(permId=1363301119, action='SELL', orderType='STP', lmtPrice=0.0, auxPrice=104.62, tif='GTC', ocaType=3, orderRef='MV', rule80A='0', trailStopPrice=104.62, openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='', clearingIntent='IB', cashQty=0.0, dontUseAutoPriceForHedge=True, autoCancelDate='20210331 17:00:00 EST', filledQuantity=26.0, refFuturesConId=2147483647, shareholder='Not an insider or substantial shareholder'), orderStatus=OrderStatus(orderId=0, status='Filled', filled=0, remaining=0, avgFillPrice=0.0, permId=0, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0), fills=[Fill(contract=Stock(conId=395196161, symbol='BILL', right='?', exchange='SMART', currency='USD', localSymbol='BILL', tradingClass='BILL'), execution=Execution(execId='0000db5b.5f96d394.01.01', time=datetime.datetime(2020, 10, 26, 17, 42, 5, tzinfo=datetime.timezone.utc), acctNumber='', exchange='IBKRATS', side='SLD', shares=26.0, price=104.45, permId=1363301119, clientId=0, orderId=61500, liquidation=0, cumQty=26.0, avgPrice=104.45, orderRef='', evRule='', evMultiplier=0.0, modelCode='', lastLiquidity=2), commissionReport=CommissionReport(execId='0000db5b.5f96d394.01.01', commission=0.418568, currency='USD', realizedPNL=-11.434868, yield_=0.0, yieldRedemptionDate=0), time=datetime.datetime(2020, 10, 26, 17, 42, 5, tzinfo=datetime.timezone.utc))], log=[TradeLogEntry(time=datetime.datetime(2020, 10, 26, 17, 42, 5, tzinfo=datetime.timezone.utc), status='Filled', message='Fill 26.0@104.45')])

thanks

**Comment by erdewit** [comment] 2020-11-03 12:30
Thanks for the bug report. It is caused by a regression in order of the initializing requests during connect; the executions should come after all the orders have been received first. This will be fixed shortly in the next version.

Note that it doesn't affect live fills, it only happens after disconnect + reconnect.

**Comment by erdewit** [comment] 2020-11-03 13:38
This fixed v0.9.64.

**Closed by erdewit** 2020-11-03 13:38 UTC
