### ISSUE TITLE
Can't create order for future data

### ISSUE THREAD

**Issue by naturalspirit-dev** [erdewit/ib_insync#591] opened 2023-05-15 08:20 UTC
Hello everyone.
This is first time to use this module.

My code are like this.

```
from ib_insync import *

# Connect to the IB API
ib = IB()
ib.connect('127.0.0.1', 7497, clientId=2)

# Define the contract for the E-mini S&P 500 Futures contract
contract = Future(symbol='ES', lastTradeDateOrContractMonth='20230616', exchange='CME_MINI_DL', currency='USD')

# Create a market order to buy 1 contract
order = MarketOrder('BUY', 1)

# Place the order
trade = ib.placeOrder(contract, order)
print(trade)

# Disconnect from IB Gateway or TWS
ib.disconnect()
```

There was no error but I can't see order in tws workstation.
Connection is successful and if I change the order for stock it works well.
Please tell me the reason and how can i fix it?

**Comment by erdewit** [comment] 2023-05-15 10:56
Duplicate of #592

**Closed by erdewit** 2023-05-15 10:56 UTC

**Comment by naturalspirit-dev** [comment] 2023-05-15 12:54
Thanks for your attention.
So please let me know how to fix it.

**Comment by naturalspirit-dev** [comment] 2023-05-15 12:56
I am waiting the answer at
https://github.com/erdewit/ib_insync/discussions/592
Please help me.
